### ISSUE TITLE
is-number-like versioning problem for nodejs not supporting ES6

### ISSUE THREAD

**Issue by Saligor** [vigour-io/is-number-like#5]
Hi,

I believe the version should be bumped to v2 allowing the tools using the older version of node to still work as expected. 

You can currently get a lot of build errors from system not able to upgrade node and relying to this package.

**Comment by jimdebeer** [comment]
hmm i thought i updated it to es5 still errors?

**Comment by jjlangholtz** [comment]
Hello @jimdebeer, it looks like 1.0.7 fixes this but is not released on npm. Any chance you could publish there as well? Thanks!

**Comment by jimdebeer** [comment]
i published it manualy -- tests are all e6 as well so failed on travis

**Comment by jimdebeer** [comment]
@Saligor resolved?

**Comment by Saligor** [comment]
Yes, working now! Thanks a lot!
