### ISSUE TITLE
'const length = val.length' breaking build

### ISSUE THREAD

**Issue by marioagarcia** [vigour-io/is-number-like#6]
Just like the other issue with const, this const usage is breaking the build.

**Comment by jimdebeer** [comment]
ah shit missed it

**Comment by NareshBanala** [comment]
I still don't see 1.0.7 version in https://www.npmjs.com/package/is-number-like

**Comment by forrestbthomas** [comment]
What this guy said^^ 
💯

**Comment by vjanssens** [comment]
Yes, please update the NPM version 👍

**Comment by marcelaerts** [comment]
I agree.

**Comment by jimdebeer** [comment]
i published manually hope it works now

**Comment by marioagarcia** [comment]
Thanks for doing that.

**Comment by NareshBanala** [comment]
Now I see new release 1.0.7 in npm. Thank you

**Comment by jimdebeer** [comment]
no prob added 0.12 as target to travis agin
